### ISSUE TITLE
Main Menu track keeps playing

### ISSUE THREAD

**Issue by NeoMax97** [LoveLiveisinBBTAG/Tekken-Jukebox-Dark-Resurrection#1]
The track selected for the main menu keeps playing, even in stages (only tested on stages w/ custom tracks). Is there a way to fix this? Thanks!

**Comment by LoveLiveisinBBTAG** [comment]
Are you sure youre using the latest version, 1.04?

**Comment by LoveLiveisinBBTAG** [comment]
Oh, I might know what it is. Try starting the jukebox after loading into the main menu. No music should play because of a bug relating to the first time the game starts, but if you load into a stage the music should play and going back to the main menu should make the main menu music play.

**Comment by NeoMax97** [comment]
That works! Thanks for the fix. Do you want to mention this somewhere, in case people run into this issue again?

**Comment by LoveLiveisinBBTAG** [comment]
The thing about starting the program before the game is already mentioned.
